# Generated by Django 3.0.4 on 2020-05-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneystats', '0002_expense_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
