# Generated by Django 3.0.4 on 2020-05-20 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneystats', '0003_auto_20200520_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='cash_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='moneystats.Check'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='price',
            field=models.FloatField(),
        ),
    ]
